spring:
  profiles: default
  output.ansi.enabled: always
  datasource:
    url: jdbc:mysql://localhost/git_gardener
    username: local_user
    password: local1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.type: trace
